export const CIDADE = {
  id: "cidade",
  name: "Cidade",
  blurb: "Cidade grande e ensolarada: avenidas conectando quarteirões, prédios institucionais e praças verdes.",
  hours: "meio-dia",
  label: "cidade",
  width: 120,
  height: 120,
  spawn: { x: 40, y: 46 },
  palette: {"floor": ["#c9b79c", "#bfa987"], "floorTrim": "#8a7f6e", "wall": "#9a8b74", "wallTop": "#b5603f", "accent": "#d9a441"},
  objects: [
      { id: "grass-1", kind: "grass", x: 1, y: 1, w: 118, h: 118 },
      { id: "path-1", kind: "path", x: 1, y: 29, w: 118, h: 4 },
      { id: "path-2", kind: "path", x: 1, y: 59, w: 118, h: 4 },
      { id: "path-3", kind: "path", x: 1, y: 89, w: 118, h: 4 },
      { id: "path-4", kind: "path", x: 29, y: 1, w: 4, h: 118 },
      { id: "path-5", kind: "path", x: 59, y: 1, w: 4, h: 118 },
      { id: "path-6", kind: "path", x: 89, y: 1, w: 4, h: 118 },
      { id: "wall-1", kind: "wall", x: 4, y: 4, w: 22, h: 1, solid: true },
      { id: "wall-2", kind: "wall", x: 4, y: 25, w: 10, h: 1, solid: true },
      { id: "wall-3", kind: "wall", x: 16, y: 25, w: 10, h: 1, solid: true },
      { id: "door-1", kind: "door", x: 14, y: 25, w: 2, h: 1 },
      { id: "wall-4", kind: "wall", x: 4, y: 5, w: 1, h: 20, solid: true },
      { id: "wall-5", kind: "wall", x: 25, y: 5, w: 1, h: 20, solid: true },
      { id: "panel-1", kind: "panel", x: 5, y: 5, w: 20, h: 20, color: "#d9a441" },
      { id: "wall-6", kind: "wall", x: 5, y: 5, w: 9, h: 1, solid: true },
      { id: "wall-7", kind: "wall", x: 5, y: 13, w: 3, h: 1, solid: true },
      { id: "wall-8", kind: "wall", x: 10, y: 13, w: 4, h: 1, solid: true },
      { id: "door-2", kind: "door", x: 8, y: 13, w: 2, h: 1 },
      { id: "wall-9", kind: "wall", x: 5, y: 6, w: 1, h: 7, solid: true },
      { id: "wall-10", kind: "wall", x: 13, y: 6, w: 1, h: 7, solid: true },
      { id: "prefeitura-reuniao", kind: "area", x: 5, y: 5, w: 9, h: 9, name: "Prefeitura — Sala de Reunião" },
      { id: "panel-2", kind: "panel", x: 6, y: 6, w: 7, h: 7, color: "#d9a441" },
      { id: "wall-11", kind: "wall", x: 15, y: 5, w: 9, h: 1, solid: true },
      { id: "wall-12", kind: "wall", x: 15, y: 13, w: 3, h: 1, solid: true },
      { id: "wall-13", kind: "wall", x: 20, y: 13, w: 4, h: 1, solid: true },
      { id: "door-3", kind: "door", x: 18, y: 13, w: 2, h: 1 },
      { id: "wall-14", kind: "wall", x: 15, y: 6, w: 1, h: 7, solid: true },
      { id: "wall-15", kind: "wall", x: 23, y: 6, w: 1, h: 7, solid: true },
      { id: "prefeitura-protocolo", kind: "area", x: 15, y: 5, w: 9, h: 9, name: "Prefeitura — Protocolo" },
      { id: "panel-3", kind: "panel", x: 16, y: 6, w: 7, h: 7, color: "#d9a441" },
      { id: "table-1", kind: "table", x: 8, y: 8, w: 3, h: 2, solid: true },
      { id: "chair-1", kind: "chair", x: 7, y: 7, w: 1, h: 2, solid: true },
      { id: "chair-2", kind: "chair", x: 11, y: 7, w: 1, h: 2, solid: true },
      { id: "board-1", kind: "board", x: 7, y: 6, w: 4, h: 1, solid: true, glow: "cyan", name: "Pauta da Reunião" },
      { id: "desk-1", kind: "desk", x: 16, y: 7, w: 4, h: 2, solid: true, name: "Balcão de Protocolo", action: "Abrir Protocolo", glow: "gold" },
      { id: "chair-3", kind: "chair", x: 17, y: 9, w: 1, h: 2, solid: true },
      { id: "shelf-1", kind: "shelf", x: 21, y: 6, w: 1, h: 3, solid: true },
      { id: "lamp-1", kind: "lamp", x: 21, y: 10, w: 1, h: 1, solid: true },
      { id: "path-7", kind: "path", x: 14, y: 26, w: 2, h: 3 },
      { id: "wall-16", kind: "wall", x: 4, y: 36, w: 22, h: 1, solid: true },
      { id: "wall-17", kind: "wall", x: 4, y: 55, w: 10, h: 1, solid: true },
      { id: "wall-18", kind: "wall", x: 16, y: 55, w: 10, h: 1, solid: true },
      { id: "door-4", kind: "door", x: 14, y: 55, w: 2, h: 1 },
      { id: "wall-19", kind: "wall", x: 4, y: 37, w: 1, h: 18, solid: true },
      { id: "wall-20", kind: "wall", x: 25, y: 37, w: 1, h: 18, solid: true },
      { id: "correios-triagem", kind: "area", x: 4, y: 36, w: 22, h: 20, name: "Correios — Triagem" },
      { id: "panel-4", kind: "panel", x: 5, y: 37, w: 20, h: 18, color: "#c97b4a" },
      { id: "desk-2", kind: "desk", x: 6, y: 38, w: 4, h: 2, solid: true, name: "Balcão dos Correios", action: "Enviar Encomenda", glow: "gold" },
      { id: "chair-4", kind: "chair", x: 7, y: 41, w: 1, h: 2, solid: true },
      { id: "table-2", kind: "table", x: 12, y: 38, w: 3, h: 2, solid: true },
      { id: "shelf-2", kind: "shelf", x: 19, y: 38, w: 1, h: 3, solid: true },
      { id: "shelf-3", kind: "shelf", x: 22, y: 38, w: 1, h: 3, solid: true },
      { id: "lamp-2", kind: "lamp", x: 14, y: 46, w: 1, h: 1, solid: true },
      { id: "path-8", kind: "path", x: 14, y: 56, w: 2, h: 3 },
      { id: "wall-21", kind: "wall", x: 4, y: 115, w: 22, h: 1, solid: true },
      { id: "wall-22", kind: "wall", x: 4, y: 96, w: 10, h: 1, solid: true },
      { id: "wall-23", kind: "wall", x: 16, y: 96, w: 10, h: 1, solid: true },
      { id: "door-5", kind: "door", x: 14, y: 96, w: 2, h: 1 },
      { id: "wall-24", kind: "wall", x: 4, y: 97, w: 1, h: 18, solid: true },
      { id: "wall-25", kind: "wall", x: 25, y: 97, w: 1, h: 18, solid: true },
      { id: "delegacia-investigacao", kind: "area", x: 4, y: 96, w: 22, h: 20, name: "Delegacia — Investigação" },
      { id: "panel-5", kind: "panel", x: 5, y: 97, w: 20, h: 18, color: "#8a7f6e" },
      { id: "desk-3", kind: "desk", x: 6, y: 98, w: 4, h: 2, solid: true, name: "Mesa de Investigação", action: "Abrir Ocorrência", glow: "purple" },
      { id: "board-2", kind: "board", x: 6, y: 102, w: 4, h: 1, solid: true, glow: "cyan", name: "Quadro de Pistas" },
      { id: "shelf-4", kind: "shelf", x: 14, y: 98, w: 1, h: 3, solid: true, name: "Arquivo" },
      { id: "chair-5", kind: "chair", x: 7, y: 100, w: 1, h: 2, solid: true },
      { id: "lamp-3", kind: "lamp", x: 19, y: 106, w: 1, h: 1, solid: true },
      { id: "path-9", kind: "path", x: 14, y: 93, w: 2, h: 3 },
      { id: "wall-26", kind: "wall", x: 36, y: 4, w: 20, h: 1, solid: true },
      { id: "wall-27", kind: "wall", x: 36, y: 25, w: 9, h: 1, solid: true },
      { id: "wall-28", kind: "wall", x: 47, y: 25, w: 9, h: 1, solid: true },
      { id: "door-6", kind: "door", x: 45, y: 25, w: 2, h: 1 },
      { id: "wall-29", kind: "wall", x: 36, y: 5, w: 1, h: 20, solid: true },
      { id: "wall-30", kind: "wall", x: 55, y: 5, w: 1, h: 20, solid: true },
      { id: "panel-6", kind: "panel", x: 37, y: 5, w: 18, h: 20, color: "#b98650" },
      { id: "wall-31", kind: "wall", x: 37, y: 5, w: 8, h: 1, solid: true },
      { id: "wall-32", kind: "wall", x: 37, y: 13, w: 3, h: 1, solid: true },
      { id: "wall-33", kind: "wall", x: 42, y: 13, w: 3, h: 1, solid: true },
      { id: "door-7", kind: "door", x: 40, y: 13, w: 2, h: 1 },
      { id: "wall-34", kind: "wall", x: 37, y: 6, w: 1, h: 7, solid: true },
      { id: "wall-35", kind: "wall", x: 44, y: 6, w: 1, h: 7, solid: true },
      { id: "biblioteca-leitura", kind: "area", x: 37, y: 5, w: 8, h: 9, name: "Biblioteca — Sala de Leitura" },
      { id: "panel-7", kind: "panel", x: 38, y: 6, w: 6, h: 7, color: "#b98650" },
      { id: "wall-36", kind: "wall", x: 46, y: 5, w: 8, h: 1, solid: true },
      { id: "wall-37", kind: "wall", x: 46, y: 13, w: 3, h: 1, solid: true },
      { id: "wall-38", kind: "wall", x: 51, y: 13, w: 3, h: 1, solid: true },
      { id: "door-8", kind: "door", x: 49, y: 13, w: 2, h: 1 },
      { id: "wall-39", kind: "wall", x: 46, y: 6, w: 1, h: 7, solid: true },
      { id: "wall-40", kind: "wall", x: 53, y: 6, w: 1, h: 7, solid: true },
      { id: "biblioteca-acervo", kind: "area", x: 46, y: 5, w: 8, h: 9, name: "Biblioteca — Acervo" },
      { id: "panel-8", kind: "panel", x: 47, y: 6, w: 6, h: 7, color: "#b98650" },
      { id: "table-3", kind: "table", x: 38, y: 7, w: 3, h: 2, solid: true },
      { id: "table-4", kind: "table", x: 38, y: 10, w: 3, h: 2, solid: true },
      { id: "chair-6", kind: "chair", x: 41, y: 7, w: 1, h: 2, solid: true },
      { id: "lamp-4", kind: "lamp", x: 42, y: 9, w: 1, h: 1, solid: true },
      { id: "shelf-5", kind: "shelf", x: 47, y: 6, w: 1, h: 3, solid: true, name: "Acervo Geral" },
      { id: "shelf-6", kind: "shelf", x: 47, y: 9, w: 1, h: 3, solid: true },
      { id: "shelf-7", kind: "shelf", x: 50, y: 6, w: 1, h: 3, solid: true },
      { id: "shelf-8", kind: "shelf", x: 50, y: 9, w: 1, h: 3, solid: true },
      { id: "path-10", kind: "path", x: 45, y: 26, w: 2, h: 3 },
      { id: "wall-41", kind: "wall", x: 36, y: 66, w: 20, h: 1, solid: true },
      { id: "wall-42", kind: "wall", x: 36, y: 85, w: 9, h: 1, solid: true },
      { id: "wall-43", kind: "wall", x: 47, y: 85, w: 9, h: 1, solid: true },
      { id: "door-9", kind: "door", x: 45, y: 85, w: 2, h: 1 },
      { id: "wall-44", kind: "wall", x: 36, y: 67, w: 1, h: 18, solid: true },
      { id: "wall-45", kind: "wall", x: 55, y: 67, w: 1, h: 18, solid: true },
      { id: "panel-9", kind: "panel", x: 37, y: 67, w: 18, h: 18, color: "#e0716a" },
      { id: "wall-46", kind: "wall", x: 37, y: 67, w: 8, h: 1, solid: true },
      { id: "wall-47", kind: "wall", x: 37, y: 74, w: 3, h: 1, solid: true },
      { id: "wall-48", kind: "wall", x: 42, y: 74, w: 3, h: 1, solid: true },
      { id: "door-10", kind: "door", x: 40, y: 74, w: 2, h: 1 },
      { id: "wall-49", kind: "wall", x: 37, y: 68, w: 1, h: 6, solid: true },
      { id: "wall-50", kind: "wall", x: 44, y: 68, w: 1, h: 6, solid: true },
      { id: "hospital-consultorio", kind: "area", x: 37, y: 67, w: 8, h: 8, name: "Hospital — Consultório" },
      { id: "panel-10", kind: "panel", x: 38, y: 68, w: 6, h: 6, color: "#e0716a" },
      { id: "wall-51", kind: "wall", x: 46, y: 67, w: 8, h: 1, solid: true },
      { id: "wall-52", kind: "wall", x: 46, y: 74, w: 3, h: 1, solid: true },
      { id: "wall-53", kind: "wall", x: 51, y: 74, w: 3, h: 1, solid: true },
      { id: "door-11", kind: "door", x: 49, y: 74, w: 2, h: 1 },
      { id: "wall-54", kind: "wall", x: 46, y: 68, w: 1, h: 6, solid: true },
      { id: "wall-55", kind: "wall", x: 53, y: 68, w: 1, h: 6, solid: true },
      { id: "hospital-recepcao", kind: "area", x: 46, y: 67, w: 8, h: 8, name: "Hospital — Recepção" },
      { id: "panel-11", kind: "panel", x: 47, y: 68, w: 6, h: 6, color: "#e0716a" },
      { id: "desk-4", kind: "desk", x: 38, y: 69, w: 4, h: 2, solid: true, name: "Consultório", action: "Consulta", glow: "green" },
      { id: "chair-7", kind: "chair", x: 39, y: 71, w: 1, h: 2, solid: true },
      { id: "shelf-9", kind: "shelf", x: 42, y: 68, w: 1, h: 3, solid: true, name: "Remédios" },
      { id: "table-5", kind: "table", x: 48, y: 69, w: 3, h: 2, solid: true },
      { id: "chair-8", kind: "chair", x: 47, y: 69, w: 1, h: 2, solid: true },
      { id: "plant-1", kind: "plant", x: 51, y: 71, w: 1, h: 2, solid: true },
      { id: "path-11", kind: "path", x: 45, y: 86, w: 2, h: 3 },
      { id: "wall-56", kind: "wall", x: 66, y: 4, w: 20, h: 1, solid: true },
      { id: "wall-57", kind: "wall", x: 66, y: 25, w: 9, h: 1, solid: true },
      { id: "wall-58", kind: "wall", x: 77, y: 25, w: 9, h: 1, solid: true },
      { id: "door-12", kind: "door", x: 75, y: 25, w: 2, h: 1 },
      { id: "wall-59", kind: "wall", x: 66, y: 5, w: 1, h: 20, solid: true },
      { id: "wall-60", kind: "wall", x: 85, y: 5, w: 1, h: 20, solid: true },
      { id: "panel-12", kind: "panel", x: 67, y: 5, w: 18, h: 20, color: "#8fae6b" },
      { id: "wall-61", kind: "wall", x: 67, y: 5, w: 8, h: 1, solid: true },
      { id: "wall-62", kind: "wall", x: 67, y: 13, w: 3, h: 1, solid: true },
      { id: "wall-63", kind: "wall", x: 72, y: 13, w: 3, h: 1, solid: true },
      { id: "door-13", kind: "door", x: 70, y: 13, w: 2, h: 1 },
      { id: "wall-64", kind: "wall", x: 67, y: 6, w: 1, h: 7, solid: true },
      { id: "wall-65", kind: "wall", x: 74, y: 6, w: 1, h: 7, solid: true },
      { id: "banco-atendimento", kind: "area", x: 67, y: 5, w: 8, h: 9, name: "Banco — Atendimento" },
      { id: "panel-13", kind: "panel", x: 68, y: 6, w: 6, h: 7, color: "#8fae6b" },
      { id: "wall-66", kind: "wall", x: 76, y: 5, w: 8, h: 1, solid: true },
      { id: "wall-67", kind: "wall", x: 76, y: 13, w: 3, h: 1, solid: true },
      { id: "wall-68", kind: "wall", x: 81, y: 13, w: 3, h: 1, solid: true },
      { id: "door-14", kind: "door", x: 79, y: 13, w: 2, h: 1 },
      { id: "wall-69", kind: "wall", x: 76, y: 6, w: 1, h: 7, solid: true },
      { id: "wall-70", kind: "wall", x: 83, y: 6, w: 1, h: 7, solid: true },
      { id: "banco-cofre", kind: "area", x: 76, y: 5, w: 8, h: 9, name: "Banco — Cofre" },
      { id: "panel-14", kind: "panel", x: 77, y: 6, w: 6, h: 7, color: "#8fae6b" },
      { id: "desk-5", kind: "desk", x: 68, y: 7, w: 4, h: 2, solid: true, name: "Guichê do Banco", action: "Abrir Conta", glow: "gold" },
      { id: "chair-9", kind: "chair", x: 69, y: 9, w: 1, h: 2, solid: true },
      { id: "plant-2", kind: "plant", x: 73, y: 6, w: 1, h: 2, solid: true },
      { id: "shelf-10", kind: "shelf", x: 77, y: 6, w: 1, h: 3, solid: true, name: "Cofre", glow: "gold" },
      { id: "shelf-11", kind: "shelf", x: 77, y: 9, w: 1, h: 3, solid: true },
      { id: "lamp-5", kind: "lamp", x: 81, y: 8, w: 1, h: 1, solid: true },
      { id: "path-12", kind: "path", x: 75, y: 26, w: 2, h: 3 },
      { id: "wall-71", kind: "wall", x: 66, y: 36, w: 20, h: 1, solid: true },
      { id: "wall-72", kind: "wall", x: 66, y: 55, w: 9, h: 1, solid: true },
      { id: "wall-73", kind: "wall", x: 77, y: 55, w: 9, h: 1, solid: true },
      { id: "door-15", kind: "door", x: 75, y: 55, w: 2, h: 1 },
      { id: "wall-74", kind: "wall", x: 66, y: 37, w: 1, h: 18, solid: true },
      { id: "wall-75", kind: "wall", x: 85, y: 37, w: 1, h: 18, solid: true },
      { id: "mercado-armazem", kind: "area", x: 66, y: 36, w: 20, h: 20, name: "Mercado — Armazém" },
      { id: "panel-15", kind: "panel", x: 67, y: 37, w: 18, h: 18, color: "#e0b464" },
      { id: "table-6", kind: "table", x: 68, y: 39, w: 3, h: 2, solid: true, name: "Mercado Municipal", glow: "gold" },
      { id: "table-7", kind: "table", x: 73, y: 39, w: 3, h: 2, solid: true },
      { id: "table-8", kind: "table", x: 78, y: 39, w: 3, h: 2, solid: true },
      { id: "bench-1", kind: "bench", x: 68, y: 46, w: 2, h: 1, solid: true },
      { id: "bench-2", kind: "bench", x: 76, y: 46, w: 2, h: 1, solid: true },
      { id: "plant-3", kind: "plant", x: 82, y: 38, w: 1, h: 2, solid: true },
      { id: "path-13", kind: "path", x: 75, y: 56, w: 2, h: 3 },
      { id: "wall-76", kind: "wall", x: 66, y: 66, w: 20, h: 1, solid: true },
      { id: "wall-77", kind: "wall", x: 66, y: 85, w: 9, h: 1, solid: true },
      { id: "wall-78", kind: "wall", x: 77, y: 85, w: 9, h: 1, solid: true },
      { id: "door-16", kind: "door", x: 75, y: 85, w: 2, h: 1 },
      { id: "wall-79", kind: "wall", x: 66, y: 67, w: 1, h: 18, solid: true },
      { id: "wall-80", kind: "wall", x: 85, y: 67, w: 1, h: 18, solid: true },
      { id: "panel-16", kind: "panel", x: 67, y: 67, w: 18, h: 18, color: "#c2504a" },
      { id: "wall-81", kind: "wall", x: 67, y: 67, w: 8, h: 1, solid: true },
      { id: "wall-82", kind: "wall", x: 67, y: 74, w: 3, h: 1, solid: true },
      { id: "wall-83", kind: "wall", x: 72, y: 74, w: 3, h: 1, solid: true },
      { id: "door-17", kind: "door", x: 70, y: 74, w: 2, h: 1 },
      { id: "wall-84", kind: "wall", x: 67, y: 68, w: 1, h: 6, solid: true },
      { id: "wall-85", kind: "wall", x: 74, y: 68, w: 1, h: 6, solid: true },
      { id: "teatro-palco", kind: "area", x: 67, y: 67, w: 8, h: 8, name: "Teatro — Palco" },
      { id: "panel-17", kind: "panel", x: 68, y: 68, w: 6, h: 6, color: "#c2504a" },
      { id: "wall-86", kind: "wall", x: 76, y: 67, w: 8, h: 1, solid: true },
      { id: "wall-87", kind: "wall", x: 76, y: 74, w: 3, h: 1, solid: true },
      { id: "wall-88", kind: "wall", x: 81, y: 74, w: 3, h: 1, solid: true },
      { id: "door-18", kind: "door", x: 79, y: 74, w: 2, h: 1 },
      { id: "wall-89", kind: "wall", x: 76, y: 68, w: 1, h: 6, solid: true },
      { id: "wall-90", kind: "wall", x: 83, y: 68, w: 1, h: 6, solid: true },
      { id: "teatro-coxia", kind: "area", x: 76, y: 67, w: 8, h: 8, name: "Teatro — Coxia" },
      { id: "panel-18", kind: "panel", x: 77, y: 68, w: 6, h: 6, color: "#c2504a" },
      { id: "table-9", kind: "table", x: 69, y: 69, w: 3, h: 2, solid: true, name: "Palco", action: "Assistir Espetáculo", glow: "gold" },
      { id: "lamp-6", kind: "lamp", x: 68, y: 68, w: 1, h: 1, solid: true },
      { id: "lamp-7", kind: "lamp", x: 73, y: 68, w: 1, h: 1, solid: true },
      { id: "shelf-12", kind: "shelf", x: 77, y: 68, w: 1, h: 3, solid: true, name: "Figurinos" },
      { id: "chair-10", kind: "chair", x: 80, y: 69, w: 1, h: 2, solid: true },
      { id: "path-14", kind: "path", x: 75, y: 86, w: 2, h: 3 },
      { id: "wall-91", kind: "wall", x: 66, y: 115, w: 20, h: 1, solid: true },
      { id: "wall-92", kind: "wall", x: 66, y: 96, w: 9, h: 1, solid: true },
      { id: "wall-93", kind: "wall", x: 77, y: 96, w: 9, h: 1, solid: true },
      { id: "door-19", kind: "door", x: 75, y: 96, w: 2, h: 1 },
      { id: "wall-94", kind: "wall", x: 66, y: 97, w: 1, h: 18, solid: true },
      { id: "wall-95", kind: "wall", x: 85, y: 97, w: 1, h: 18, solid: true },
      { id: "panel-19", kind: "panel", x: 67, y: 97, w: 18, h: 18, color: "#b5603f" },
      { id: "wall-96", kind: "wall", x: 67, y: 114, w: 8, h: 1, solid: true },
      { id: "wall-97", kind: "wall", x: 67, y: 107, w: 3, h: 1, solid: true },
      { id: "wall-98", kind: "wall", x: 72, y: 107, w: 3, h: 1, solid: true },
      { id: "door-20", kind: "door", x: 70, y: 107, w: 2, h: 1 },
      { id: "wall-99", kind: "wall", x: 67, y: 108, w: 1, h: 6, solid: true },
      { id: "wall-100", kind: "wall", x: 74, y: 108, w: 1, h: 6, solid: true },
      { id: "estacao-hall", kind: "area", x: 67, y: 107, w: 8, h: 8, name: "Estação — Hall" },
      { id: "panel-20", kind: "panel", x: 68, y: 108, w: 6, h: 6, color: "#b5603f" },
      { id: "wall-101", kind: "wall", x: 76, y: 114, w: 8, h: 1, solid: true },
      { id: "wall-102", kind: "wall", x: 76, y: 107, w: 3, h: 1, solid: true },
      { id: "wall-103", kind: "wall", x: 81, y: 107, w: 3, h: 1, solid: true },
      { id: "door-21", kind: "door", x: 79, y: 107, w: 2, h: 1 },
      { id: "wall-104", kind: "wall", x: 76, y: 108, w: 1, h: 6, solid: true },
      { id: "wall-105", kind: "wall", x: 83, y: 108, w: 1, h: 6, solid: true },
      { id: "estacao-bilheteria", kind: "area", x: 76, y: 107, w: 8, h: 8, name: "Estação — Bilheteria" },
      { id: "panel-21", kind: "panel", x: 77, y: 108, w: 6, h: 6, color: "#b5603f" },
      { id: "bench-3", kind: "bench", x: 68, y: 109, w: 2, h: 1, solid: true },
      { id: "bench-4", kind: "bench", x: 68, y: 111, w: 2, h: 1, solid: true },
      { id: "plant-4", kind: "plant", x: 72, y: 108, w: 1, h: 2, solid: true },
      { id: "desk-6", kind: "desk", x: 77, y: 109, w: 4, h: 2, solid: true, name: "Bilheteria", action: "Comprar Passagem", glow: "gold" },
      { id: "chair-11", kind: "chair", x: 78, y: 111, w: 1, h: 2, solid: true },
      { id: "path-15", kind: "path", x: 75, y: 93, w: 2, h: 3 },
      { id: "wall-106", kind: "wall", x: 96, y: 36, w: 20, h: 1, solid: true },
      { id: "wall-107", kind: "wall", x: 96, y: 55, w: 9, h: 1, solid: true },
      { id: "wall-108", kind: "wall", x: 107, y: 55, w: 9, h: 1, solid: true },
      { id: "door-22", kind: "door", x: 105, y: 55, w: 2, h: 1 },
      { id: "wall-109", kind: "wall", x: 96, y: 37, w: 1, h: 18, solid: true },
      { id: "wall-110", kind: "wall", x: 115, y: 37, w: 1, h: 18, solid: true },
      { id: "panel-22", kind: "panel", x: 97, y: 37, w: 18, h: 18, color: "#d98c4a" },
      { id: "wall-111", kind: "wall", x: 97, y: 37, w: 8, h: 1, solid: true },
      { id: "wall-112", kind: "wall", x: 97, y: 44, w: 3, h: 1, solid: true },
      { id: "wall-113", kind: "wall", x: 102, y: 44, w: 3, h: 1, solid: true },
      { id: "door-23", kind: "door", x: 100, y: 44, w: 2, h: 1 },
      { id: "wall-114", kind: "wall", x: 97, y: 38, w: 1, h: 6, solid: true },
      { id: "wall-115", kind: "wall", x: 104, y: 38, w: 1, h: 6, solid: true },
      { id: "escola-sala", kind: "area", x: 97, y: 37, w: 8, h: 8, name: "Escola — Sala de Aula" },
      { id: "panel-23", kind: "panel", x: 98, y: 38, w: 6, h: 6, color: "#d98c4a" },
      { id: "wall-116", kind: "wall", x: 106, y: 37, w: 8, h: 1, solid: true },
      { id: "wall-117", kind: "wall", x: 106, y: 44, w: 3, h: 1, solid: true },
      { id: "wall-118", kind: "wall", x: 111, y: 44, w: 3, h: 1, solid: true },
      { id: "door-24", kind: "door", x: 109, y: 44, w: 2, h: 1 },
      { id: "wall-119", kind: "wall", x: 106, y: 38, w: 1, h: 6, solid: true },
      { id: "wall-120", kind: "wall", x: 113, y: 38, w: 1, h: 6, solid: true },
      { id: "escola-professores", kind: "area", x: 106, y: 37, w: 8, h: 8, name: "Escola — Sala dos Professores" },
      { id: "panel-24", kind: "panel", x: 107, y: 38, w: 6, h: 6, color: "#d98c4a" },
      { id: "desk-7", kind: "desk", x: 98, y: 39, w: 4, h: 2, solid: true },
      { id: "chair-12", kind: "chair", x: 99, y: 41, w: 1, h: 2, solid: true },
      { id: "board-3", kind: "board", x: 98, y: 38, w: 4, h: 1, solid: true, glow: "cyan", name: "Quadro da Sala" },
      { id: "table-10", kind: "table", x: 108, y: 39, w: 3, h: 2, solid: true },
      { id: "chair-13", kind: "chair", x: 107, y: 39, w: 1, h: 2, solid: true },
      { id: "shelf-13", kind: "shelf", x: 111, y: 38, w: 1, h: 3, solid: true },
      { id: "path-16", kind: "path", x: 105, y: 56, w: 2, h: 3 },
      { id: "tree-1", kind: "tree", x: 96, y: 4, w: 3, h: 3, solid: true },
      { id: "tree-2", kind: "tree", x: 112, y: 4, w: 3, h: 3, solid: true },
      { id: "tree-3", kind: "tree", x: 96, y: 20, w: 3, h: 3, solid: true },
      { id: "tree-4", kind: "tree", x: 112, y: 20, w: 3, h: 3, solid: true },
      { id: "hedge-1", kind: "hedge", x: 99, y: 10, w: 6, h: 1, solid: true },
      { id: "hedge-2", kind: "hedge", x: 99, y: 16, w: 6, h: 1, solid: true },
      { id: "flower-1", kind: "flower", x: 104, y: 4, w: 3, h: 2 },
      { id: "flower-2", kind: "flower", x: 104, y: 20, w: 3, h: 2 },
      { id: "bench-5", kind: "bench", x: 100, y: 13, w: 2, h: 1, solid: true },
      { id: "bench-6", kind: "bench", x: 112, y: 13, w: 2, h: 1, solid: true },
      { id: "lamp-8", kind: "lamp", x: 98, y: 8, w: 1, h: 1, solid: true },
      { id: "lamp-9", kind: "lamp", x: 114, y: 8, w: 1, h: 1, solid: true },
      { id: "fountain-1", kind: "fountain", x: 43, y: 43, w: 4, h: 4, solid: true, shape: "circle", glow: "gold", name: "Fonte Central", action: "Fazer um pedido" },
      { id: "bench-7", kind: "bench", x: 36, y: 40, w: 2, h: 1, solid: true },
      { id: "bench-8", kind: "bench", x: 52, y: 40, w: 2, h: 1, solid: true },
      { id: "bench-9", kind: "bench", x: 36, y: 50, w: 2, h: 1, solid: true },
      { id: "bench-10", kind: "bench", x: 52, y: 50, w: 2, h: 1, solid: true },
      { id: "hedge-3", kind: "hedge", x: 36, y: 35, w: 6, h: 1, solid: true },
      { id: "hedge-4", kind: "hedge", x: 46, y: 35, w: 6, h: 1, solid: true },
      { id: "hedge-5", kind: "hedge", x: 36, y: 55, w: 6, h: 1, solid: true },
      { id: "hedge-6", kind: "hedge", x: 46, y: 55, w: 6, h: 1, solid: true },
      { id: "flower-3", kind: "flower", x: 34, y: 44, w: 3, h: 2 },
      { id: "flower-4", kind: "flower", x: 51, y: 44, w: 3, h: 2 },
      { id: "lamp-10", kind: "lamp", x: 40, y: 48, w: 1, h: 1, solid: true },
      { id: "lamp-11", kind: "lamp", x: 48, y: 48, w: 1, h: 1, solid: true },
      { id: "rug-1", kind: "rug", x: 8, y: 66, w: 14, h: 10, color: "rgba(217,164,65,0.18)" },
      { id: "jukebox-1", kind: "jukebox", x: 4, y: 68, w: 2, h: 2, solid: true, name: "Jukebox da Praça", action: "Tocar playlist", glow: "gold" },
      { id: "bench-11", kind: "bench", x: 10, y: 70, w: 2, h: 1, solid: true },
      { id: "bench-12", kind: "bench", x: 18, y: 70, w: 2, h: 1, solid: true },
      { id: "bench-13", kind: "bench", x: 10, y: 78, w: 2, h: 1, solid: true },
      { id: "bench-14", kind: "bench", x: 18, y: 78, w: 2, h: 1, solid: true },
      { id: "lamp-12", kind: "lamp", x: 6, y: 72, w: 1, h: 1, solid: true },
      { id: "lamp-13", kind: "lamp", x: 22, y: 72, w: 1, h: 1, solid: true },
      { id: "flower-5", kind: "flower", x: 4, y: 80, w: 3, h: 2 },
      { id: "flower-6", kind: "flower", x: 20, y: 80, w: 3, h: 2 },
      { id: "tree-5", kind: "tree", x: 96, y: 66, w: 3, h: 3, solid: true },
      { id: "tree-6", kind: "tree", x: 112, y: 66, w: 3, h: 3, solid: true },
      { id: "tree-7", kind: "tree", x: 96, y: 82, w: 3, h: 3, solid: true },
      { id: "tree-8", kind: "tree", x: 112, y: 82, w: 3, h: 3, solid: true },
      { id: "hedge-7", kind: "hedge", x: 99, y: 72, w: 6, h: 1, solid: true },
      { id: "hedge-8", kind: "hedge", x: 99, y: 78, w: 6, h: 1, solid: true },
      { id: "flower-7", kind: "flower", x: 104, y: 66, w: 3, h: 2 },
      { id: "flower-8", kind: "flower", x: 104, y: 82, w: 3, h: 2 },
      { id: "bench-15", kind: "bench", x: 100, y: 75, w: 2, h: 1, solid: true },
      { id: "bench-16", kind: "bench", x: 112, y: 75, w: 2, h: 1, solid: true },
      { id: "lamp-14", kind: "lamp", x: 98, y: 70, w: 1, h: 1, solid: true },
      { id: "lamp-15", kind: "lamp", x: 114, y: 70, w: 1, h: 1, solid: true },
      { id: "flower-9", kind: "flower", x: 36, y: 96, w: 3, h: 2 },
      { id: "flower-10", kind: "flower", x: 48, y: 96, w: 3, h: 2 },
      { id: "flower-11", kind: "flower", x: 36, y: 108, w: 3, h: 2 },
      { id: "flower-12", kind: "flower", x: 48, y: 108, w: 3, h: 2 },
      { id: "flower-13", kind: "flower", x: 42, y: 102, w: 3, h: 2 },
      { id: "bench-17", kind: "bench", x: 40, y: 100, w: 2, h: 1, solid: true },
      { id: "bench-18", kind: "bench", x: 40, y: 112, w: 2, h: 1, solid: true },
      { id: "lamp-16", kind: "lamp", x: 34, y: 102, w: 1, h: 1, solid: true },
      { id: "lamp-17", kind: "lamp", x: 54, y: 102, w: 1, h: 1, solid: true },
      { id: "hedge-9", kind: "hedge", x: 36, y: 116, w: 6, h: 1, solid: true },
      { id: "water-1", kind: "water", x: 96, y: 96, w: 10, h: 8, solid: true },
      { id: "tree-9", kind: "tree", x: 110, y: 96, w: 3, h: 3, solid: true },
      { id: "tree-10", kind: "tree", x: 96, y: 110, w: 3, h: 3, solid: true },
      { id: "tree-11", kind: "tree", x: 112, y: 112, w: 3, h: 3, solid: true },
      { id: "bench-19", kind: "bench", x: 100, y: 108, w: 2, h: 1, solid: true },
      { id: "bench-20", kind: "bench", x: 108, y: 100, w: 2, h: 1, solid: true },
      { id: "flower-14", kind: "flower", x: 108, y: 108, w: 3, h: 2 },
      { id: "lamp-18", kind: "lamp", x: 104, y: 104, w: 1, h: 1, solid: true },
  ],
}
